"""Batch D audit: map every fitted M6 feature to its docs/M6.md §1 planned variable.

Emits analysis/geomatics_integration_v1/M6_CORE_FEATURE_MANIFEST.yaml.
Asserts every fitted column is assigned exactly once, so the manifest cannot
silently drift from the design matrix.
"""
import hashlib
import json
import re
from pathlib import Path

import pandas as pd

REPO = Path("/Users/mpcr/aj/Dengue/srilanka-dengue-ews-calibration")
QUAR = REPO / "data_quarantine" / "m6_geomatics"
OUT = REPO / "analysis" / "geomatics_integration_v1"

# (planned variable #, name, batch, matcher) — order matters, first match wins.
RULES = [
    (1,  "Elevation",                       "A", r"^elev_"),
    (2,  "Slope",                           "A", r"^slope_"),
    (3,  "Topographic Wetness Index",       "A", r"^twi_"),
    (4,  "HAND",                            "A", r"^hand_"),
    (8,  "Land-cover fragmentation",        "B", r"^(lc_shannon|edge_density_m_km2|lpi_pct|built_lpi_pct)$"),
    (5,  "Built-up / impervious",           "B", r"^frac_built$"),
    (6,  "Population density",              "B", r"^(pop_sum|pop_density_km2)$"),
    (7,  "Nighttime lights",                "B", r"^nightlight_mean$"),
    # frac_water is the IO LULC water class, not JRC — same concept, different product.
    (11, "Surface water / NDWI",            "B", r"^(water_frac|permanent_water_frac|water_occurrence_mean|dist_permanent_water_km|frac_water)$"),
    (12, "Forest cover",                    "B", r"^frac_trees$"),
    (9,  "Land-surface temperature / UHI",  "C", r"^lst_"),
    (10, "NDVI / EVI greenness",            "C", r"^(ndvi|evi)_"),
    # Batch D — only the static half of #16 is present, and via a different product.
    (16, "Rice paddy / cropland",           "D", r"^frac_crops$"),
    # Not among the 16: co-extracted LULC class fractions.
    (None, "Unplanned co-extracted LULC class", None, r"^frac_(bare|rangeland|flooded_veg)$"),
]


def assign(feat):
    for num, name, batch, pat in RULES:
        if re.search(pat, feat):
            return num, name, batch
    raise KeyError(f"unassigned feature: {feat}")


def sha16(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


coef = pd.read_csv(QUAR / "m6_coefficients_srilanka_v1.csv")
feats = coef.feature.tolist()
assert len(feats) == len(set(feats)) == 92, len(feats)

rows = []
for f in feats:
    num, name, batch = assign(f)
    rows.append({"feature": f, "planned_var": num, "planned_name": name, "batch": batch})
df = pd.DataFrame(rows)

# every planned variable that is fully absent
present = {r["planned_var"] for r in rows if r["planned_var"]}
planned = {
    1: ("Elevation", "A"), 2: ("Slope", "A"), 3: ("Topographic Wetness Index", "A"),
    4: ("HAND", "A"), 5: ("Built-up / impervious", "B"), 6: ("Population density", "B"),
    7: ("Nighttime lights", "B"), 8: ("Land-cover fragmentation", "B"),
    9: ("Land-surface temperature / UHI", "C"), 10: ("NDVI / EVI greenness", "C"),
    11: ("Surface water / NDWI", "B"), 12: ("Forest cover", "B"),
    13: ("Human mobility / connectivity", "D"), 14: ("Socioeconomic / wealth", "D"),
    15: ("Healthcare access", "D"), 16: ("Rice paddy / cropland", "D"),
}
absent = sorted(set(planned) - present)

lines = []
add = lines.append
add("# M6 feature manifest — Batch D audit")
add("# Generated by the Batch D column audit (instruction_m6.md §2).")
add("# Maps every column of the fitted M6 design matrix to its docs/M6.md §1 planned variable.")
add("")
add("model_label: M6-core (A/B/C)")
add("source_commit: ff6287d0e336ab4e3a3d178593d3bb28e3f33a21")
add("country: sri_lanka")
add("design_matrix:")
add(f"  n_features: {len(feats)}")
add("  estimator: LogisticRegression(penalty=l2, C=0.001, solver=lbfgs)")
add("  feature_selection: none  # L2 only; 0 of 92 coefficients are zero")
add(f"  coefficients_sha256_16: {sha16(QUAR / 'm6_coefficients_srilanka_v1.csv')}")
add(f"  features_table_sha256_16: {sha16(QUAR / 'm6_features_weekly_srilanka_v1.csv')}")
add(f"  rowset_sha256_16: {sha16(QUAR / 'm6_rowset_srilanka_v1.csv')}")
add("")
add("batches_present:")
for b in ["A", "B", "C"]:
    sub = df[df.batch == b]
    pv = sorted(int(v) for v in set(sub.planned_var))
    add(f"  {b}: {{n_features: {len(sub)}, planned_vars: {pv}}}")
add("")
add("batch_D_status: ABSENT_AS_DESIGNED")
add("batch_D_detail:")
add("  13_mobility_connectivity: absent    # no gravity in-flow / centrality features built")
add("  14_socioeconomic_wealth: absent     # no Meta RWI, no nightlights+built SES proxy")
add("  15_healthcare_access: absent        # no travel-time or distance-to-facility surface")
add("  16_rice_paddy_cropland: partial     # see below")
add("  16_partial_note: >-")
add("    frac_crops is present, but it is one of seven Impact Observatory io-lulc-annual-v02")
add("    class fractions co-extracted wholesale by notebook 03 (Batch B), not a deliberate")
add("    Batch D build. Two departures from M6.md 6.16: the product is Impact Observatory,")
add("    not ESA WorldCover; and the EVI phenology amplitude (seasonal max-min paddy-intensity")
add("    proxy) that 6.16 pairs with the cropland share was never built. The static share is")
add("    therefore present incidentally and the seasonal half is absent.")
add("")
add(f"planned_variables_fully_absent: {absent}")
add("")
add("product_departures_from_M6_md:")
add("  land_cover_product: >-")
add("    M6.md 1 names ESA WorldCover / GHSL for the land-cover-derived variables (5, 8, 12, 16).")
add("    The executed build used Impact Observatory io-lulc-annual-v02 (10 m) throughout")
add("    (notebook 03). frac_water therefore measures planned variable 11 via the LULC class")
add("    vector rather than the JRC Global Surface Water layer that 6.11 specifies; the JRC")
add("    layer is also present, as water_occurrence_mean / permanent_water_frac.")
add("  uhi_variant: >-")
add("    6.9's optional UHI variant (unit LST minus rural-ring LST) was not built. Only the")
add("    direct LST statistics are present. 6.9 marks it optional, so this is not a departure")
add("    from a requirement.")
add("")
add("unplanned_features:")
add("  # Co-extracted LULC classes not enumerated among the 16.")
for f in sorted(df[df.planned_var.isna()].feature):
    add(f"  - {f}")
add("")
add("features:")
for _, r in df.sort_values(["batch", "planned_var", "feature"], na_position="last").iterrows():
    v = "null" if pd.isna(r.planned_var) else int(r.planned_var)
    b = "null" if r.batch is None or pd.isna(r.batch) else r.batch
    add(f"  - {{name: {r.feature}, planned_var: {v}, batch: {b}}}")

OUT.mkdir(parents=True, exist_ok=True)
(OUT / "M6_CORE_FEATURE_MANIFEST.yaml").write_text("\n".join(lines) + "\n")

print("batch counts:\n", df.groupby("batch", dropna=False).size().to_string())
print("\nfully absent planned variables:", absent)
print("unplanned:", sorted(df[df.planned_var.isna()].feature))
print("\nwrote", OUT / "M6_CORE_FEATURE_MANIFEST.yaml")
